pipeline {
    agent any
    
    tools {
        maven 'maven3' 
        jdk 'java' 
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm // This correctly grabs the code from the repo configured in the Job
            }
        }
        
        stage('Build & Test') {
            steps {
                dir('Cucumber_BBD') { // Change this to match the folder where pom.xml exists
            bat 'mvn clean test -Dheadless=true'
        }
            }
        }
    }
    
    post {
        always {
            publishHtml(target: [
            reportDir: 'Cucumber_BBD/target/htmlreports', // Ensure path matches where report is generated
            reportFiles: 'Parabank_report.html',
            reportName: 'Cucumber BBD Report',
            alwaysLinkToLastBuild: true
        ])
        }
    }
}